package org.heuros.core.ga.chromosome;

/**
 * Factory class for the chromosome objects.
 * 
 */
public interface ChromosomeFactory<T> {

	public ChromosomeFactory<T> setChromosomeLength(int value);

    /**
     * Gives the length of the chromosome objects which will be generated by 
     * this chromosome factory object.
     * 
     * @return int length of the generated chromosomes.
     */
    public int getChromosomeLength();

    /**
     * Generates a chromosome object.
     * 
     * @return IChromosome generated chromosome object.
     */
    public Chromosome<T> createChromosome();
}
